### ISSUE TITLE
Mobile scaling problems

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#101]
On a mobile device (iPhone 6), the day view looks really good, but the month view does not resize properly. In portrait mode I need to scroll to get the right hand side of the planner and the navigation menu is completely missing. In landscape mode it is almost perfect, the only issue being the navigation menu overlaps the planner slightly. Point to note, this is orders of magnitude better than trying to view an excel spreadsheet on a phone.

**Comment by pjfl** [comment]
In portrait mode the right side navigation is meant to disappear. It is replaced by the select element which displays as "Navigate the application..."

**Comment by pjfl** [comment]
Since in portrait mode nothing is overlapping, everything is accessible, and the horizontal scrolling is inevitable given the size of the table (which is not compressible), I won't be making any changes to this view.

**Comment by pjfl** [comment]
In landscape mode the overlapping of the planner and the navigation needs to be fixed since it looks bad and prevents proper operation.
