### ISSUE TITLE
Indication of the completeness of each day on the month view

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#103]
Would conditional formatting on the days be possible/useful? Perhaps a RAG status in the cell where the date is in the month view? Red is no duties are taken, amber where some are and green when all slots filled. I know that it is fairly obvious what is taken and what isn’t, but perhaps giving an “at a glance” status might be useful…

My thoughts are that we might 
1. solid R/A/G colour for the background of the day number square
2. tint the background of the whole day
3. solid colour outline for the day.
4. do nothing

**Comment by JB62** [comment]
Don't know too be honest. I've just been passing on comments from those that have had a look about. 

Can we just assume weekdays are night only, weekends are 24 hours?

**Comment by pjfl** [comment]
So it will be right for all days except bank holidays

**Comment by JB62** [comment]
Yep. Just have to suck it up for the bank holidays.
