### ISSUE TITLE
Support for training programs

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#104]
For organising training, it would be very useful to have an at-a-glance view of group training progress together.  This is currently a spreadsheet, with a row for each person, and a column for each training program. Currently these are GMP, North Route, South Route, Road Assessment, Controller Training, Towing Assessment, but there could be others. 

This view only needs to show those "in training", but I'm not sure how to determine that and I think the title of the ticket belies quite a schema update unfortunately, but I think it would be an excellent addition to the system if we get it right..

Perhaps an field on the certification table to indicate an "in-house" certification that would appear as a column in the list as a start.

Need some more roles, one for each of the "in-house" certifications, so that individual trainers and attendees can be assigned to each training "event".  ...which implies we need a new event type - "training".  The training manager role should be the only one that can create or edit training events, and it must be able to restrict numbers of attendees. The training manager would assign trainers to each training event.

On the rota calendar, there should be some indication that there is a training event on that day and not just rely on the normal "there are events" marker.

**Comment by JB62** [comment]
Thoughts:  

The certifications expanded allow progress in that certification. People could then subscribe (or be subscribed) to any or all certifications, with only those that are "complete" showing up as a persons certifications as they currently stand. 

A view of these certifications (spreadsheet-like) would show a column for each available, with a row for each person subscribed to at least one of those courses. The intersecting cell would then show the persons progress in that certification; subscribed, started, in-progress, complete, expired (with the appropriate date). Option to hide/show rows that are complete/in-progress/expired. Probably default to hiding rows where the only subscriptions are complete more than N days ago. 

Training Manager role should be able to edit the progress states.

**Comment by pjfl** [comment]
Some of that is already done in the training branch. Just need to add the states as coloured backgrounds

Will need to add a UI feature to allow the horizontal scrolling of the table since there are already more
courses than we have room to display them

**Comment by pjfl** [comment]
Need to add colour to caption on summary screen

**Comment by pjfl** [comment]
Filter rows to suppress complted by default

**Comment by pjfl** [comment]
When course completed offer option to add role/certification

**Comment by pjfl** [comment]
Instead of deleting training record when removing course flag it as deleted and provide a per person
history of deleted courses

**Comment by pjfl** [comment]
Add button to update dialog to add and remove training course causing a reset

**Comment by pjfl** [comment]
Clicking on blank cells in summary view enroles user on course
