### ISSUE TITLE
Vehicle report date fields slightly to short

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#113]
From  01/01/2016 To  21/10/2016    is currently displaying as
From  01/01/201 To  21/10/201   unless you scroll the text

**Comment by pjfl** [comment]
Not for me. What have you got your zoom % set to?

**Comment by JB62** [comment]
100%

**Comment by pjfl** [comment]
This is working for me https://notitia.j-bg.co.uk/notitia/vehicles-report?period=year-to-date

**Comment by JB62** [comment]
![image](https://cloud.githubusercontent.com/assets/16360425/19621273/2b9f4660-9886-11e6-8f46-2fb1a18d8581.png)

**Comment by JB62** [comment]
100℅

⁣​
