### ISSUE TITLE
Certs and Training columns should be available for all people

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#114]
...not just riders/controllers - fundraisers also do GMP, possibly others

**Comment by pjfl** [comment]
Do you really mean all people. Be specific

**Comment by JB62** [comment]
Yes. Everyone. Anyone can do a training session, everyone does GMP, and GMP leads to a "cert"

**Comment by pjfl** [comment]
Even though they are *not* a controller, driver, fund_raiser, or rider?

**Comment by JB62** [comment]
Everyone (with a couple of specific exceptions) will be one of those (unless you've resigned/are inactive) - everyone does GMP.
