### ISSUE TITLE
Event location

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#121]
Events could allow a location postcode so that their location doesn't necessarily match that of the event owner - at the menders for a week for instance. That way the distance calculation could be more accurate when a bike is going directly from the event to a new keeper.

**Comment by pjfl** [comment]
Schema change required. Location object gets postcode and co-ordinates (optional attributes), and the event object gets an optional location attribute

**Comment by pjfl** [comment]
Schema change implemented
