### ISSUE TITLE
Spreadsheet view columns

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#123]
Remove the "shift" column from each day and add it once to the start of each row, making the overall width of the SS less. Increase the border between the SS and the window edge, perhaps to about the same width of one of the "shift" columns just removed.

**Comment by pjfl** [comment]
We've talked about this before. Where should I put the mouseover tip text that appears for vehicle events?

**Comment by JB62** [comment]
The R or C4 column? You suggested the person label? I guess it doesn't really matter much - maybe the whole cell?

**Comment by pjfl** [comment]
Person label it is
