### ISSUE TITLE
Training event view

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#126]
Everyone should be able to see some sort of calendar or similar of training (and possibly other) events to which they have subscribed or in which they intend to participate

**Comment by pjfl** [comment]
How about a link on the month rota next to "My Slots" called "My Events"? Brings up a dialog of links which will take your to the fund raising / training event summary

**Comment by JB62** [comment]
Sounds like a plan. I think the dialog should indicate the date of the event without having to click the link to find out though.
