### ISSUE TITLE
Incomplete requests should be available to later controllers

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#131]
In the event that a request spans more than one duty (Friday night -> Saturday day for example), the controller taking over should have full access to the request as though they had created it so that they can complete it.

**Comment by pjfl** [comment]
They are available to the call_viewer role

**Comment by JB62** [comment]
But we don't want all calls visible to all controllers - we don't want to assign that role to everyone. ⁣​

**Comment by pjfl** [comment]
Awkward

**Comment by JB62** [comment]
I guess we can determine if a controller is on-shift,  so can we not just allow incomplete requests to effectively owned by the "current" controller?

**Comment by pjfl** [comment]
Current controller becomes a temporary call_viewer
