### ISSUE TITLE
jobdaemon log

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#134]
...should include destination email address (for email jobs)

**Comment by pjfl** [comment]
Overkill. It's on the person record. It's not like they change much and besides the important bit is the message id which came from the mail system and "proves" that the email was sent

**Comment by JB62** [comment]
Not really - you just get "Job send_message-74 rv 0"  but you've no idea who that was to, or what the message was about

**Comment by pjfl** [comment]
Your looking in the wrong log file. Look in the util log

**Comment by JB62** [comment]
Ah, okay.
