### ISSUE TITLE
Uneven cell widths in month rota

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#135]
The "north" cell always seems to be a rectangle while the others are squares. Looks odd, but ultimately not a hair on fire problem.  Seems to be manually fixable by adding 

   \<colgroup>
     \<col width="xx">
     ...
   \</colgroup>

values in the month-rota table class, but that may not be the ultimate fix.

**Comment by pjfl** [comment]
This is an artifact of the way browsers implement colspan and as such nothing can be done to alter that
