### ISSUE TITLE
Allocation of 4 wheel vehicles

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#136]
At some point, it's not infeasible that we'll need to allocate service cars as well as bikes. While not immediately a requirement, the driver slot might need to allow the same vehicle request and allocation options as bike slots.

**Comment by pjfl** [comment]
I have created a wiki issue for this as that is a more appropriate list

**Comment by JB62** [comment]
This will become necessary in January.

**Comment by pjfl** [comment]
What type of vehicle do you want listed in the assign vehicle dialog for a driver? For a rider it's obviously type bike, but for driver we have car and 4x4

**Comment by JB62** [comment]
Both ideally - just a serv owned 4 wheel vehicle really, no need to differentiate for the moment for allocation purposes.

**Comment by JB62** [comment]
Can we list both four wheel vehicle types to be assigned...

DayRota.pm:528        my $vehicle_type = $slot->type_name eq 'driver' ? '4x4' 

forces it to only list 4x4 vehicles.

**Comment by pjfl** [comment]
I assume you mean can we list type car and 4x4. The short answer is no, but I'll look at it

**Comment by JB62** [comment]
Can the vehicle type be "car" and 4x4 an attribute of a car?⁣​

**Comment by pjfl** [comment]
No

**Comment by JB62** [comment]
Sorry. Seemed a good idea to me - just an "is fwd" attribute on vehicle, you always allocate a 'car'. Personal cars are, well, cars and if either has the fwd attribute, it's displayed as such.

**Comment by pjfl** [comment]
This is now patched to display both cars and 4x4. The feature will not start working until the next release of Web::ComposableRequest

**Comment by JB62** [comment]
Only seems to list cars not 4x4 now

**Comment by pjfl** [comment]
Read the comment

**Comment by JB62** [comment]
I did.
john@john-laptop:~/Notitia$ cpanm --notest Web::ComposableRequest
Web::ComposableRequest is up to date. (0.17.1)

**Comment by pjfl** [comment]
The next release of W::CR will be 0.18.1 which I haven't released yet, which is why the feature doesn't work yet

**Comment by pjfl** [comment]
Try

    cpanm git://github.com/pjfl/p5-web-composablerequest.git

if your really keen

**Comment by JB62** [comment]
When are you going to push out 0.18.1 ?

**Comment by pjfl** [comment]
January
