### ISSUE TITLE
Call log

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#137]
Calls to our on call number generate notification  email to a mailbox. It would be useful to the controllers if we could display the call history by scraping these emails - connect to an imap account, read the latest emails and parse out the calling number and time, and display those data on a controller-accessible page in the app.

**Comment by JB62** [comment]
I have a bunch of code that calculates bank holidays and whether or not a day is a working one

**Comment by pjfl** [comment]
Moved to the wiki since this is not an actionable ticket
