### ISSUE TITLE
Add validation criteria to data validation exceptions

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#145]
Not strictly a  bug, but...

Create a new Incident, choose  "other" as the category
Enter some description of the category - I used "Inexplicable road rage"
Submit the data
Get presented with...

I'm sorry Admin, I can't do that
Form validation errors
Parameter 'category_other' has an invalid length

It would be very useful if the user was told what a valid length is (from the code, I can see it's between 3 and 16 chars, but it's not obvious without reading the code).

**Comment by pjfl** [comment]
So you could add some field help explaining that

**Comment by JB62** [comment]
In general, I think it would be good if validation error messages gave the criteria against which the validation failed.
