### ISSUE TITLE
Page editing permissions

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#146]
If you have "event_manager" role, the "improve this page" menu is accessible, but it shows all the commands (create/delete/upload...) but the event_manager only has permissions to execute upload. It would be much better if only those menu items that were permitted were visible

**Comment by JB62** [comment]
Thinking about it, why does event manager need to upload?

**Comment by JB62** [comment]
See pull request 147

**Comment by pjfl** [comment]
Apart from the undocumented variables, really what is the point. Apart from upload you've got the same values for the other config attributes. So your going to allow one group of users to create but not edit?

**Comment by JB62** [comment]
Possibly yes. It was the delete I was particularly wanting to protect.  Why does event_manager need upload?

**Comment by pjfl** [comment]
They have create / delete / rename / save for the posts, upload came along as part of the set but it should not be needed

**Comment by JB62** [comment]
So if Role(event_manager) and Role(person_manager) can be removed from

  lib/App/Notitia/Model/Documentation.pm:sub upload : Role(editor) Role(event_manager) Role(person_manager)

then this is not necessary after all that

**Comment by pjfl** [comment]
The person_manager uploads mugshots

**Comment by JB62** [comment]
...but not from a document page? I which case is_editor should not include person_manager (or event_manager) so the shade menu isn't there without editor role?

**Comment by JB62** [comment]
...but not from a document page? I which case is_editor should not include person_manager (or event_manager) so the shade menu isn't there without editor role?

**Comment by JB62** [comment]
All we need to do is remove event_manager and person_manager from the editors array, and we're grand.
