### ISSUE TITLE
Claim slot dialog too wide in mobile mode

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#150]
When claiming a slot on a mobile, the claim dialog appears but largely off-screen as it's wider than the screen. Also, if it is a slot at the bottom of the page, it's not obvious it's appeared at all as it's entirely of screen at the to of the page.

Perhaps the field labels can be above the fields rather than to the left, and the dialog appear anchored to the control that triggered it?

**Comment by pjfl** [comment]
Have you tried it in landscape?

**Comment by JB62** [comment]
Yes. It fits width ways, just, but still appears off screen at the to of the page

**Comment by JB62** [comment]
This would fit better, if I could work out how to do it for real. Needs to be anchored vertically to the link that created it

![dialog](https://cloud.githubusercontent.com/assets/16360425/21999673/34600384-dc33-11e6-83a3-0089ff713344.png)

**Comment by JB62** [comment]
Can we add (if available) to the Personal Vehicle to indicate that it's optional?

**Comment by pjfl** [comment]
Fixed in v0.11.30
