### ISSUE TITLE
Scrolling month rota in mobile view painful

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#151]
When the month view is wider than a mobile screen, dragging the page left or right to view the remaining days is extremely slow and jerky. It gives the appearance of having to go back to the server to render the page every pixel.

**Comment by JB62** [comment]
Wierdly, scrolling vertically is completely fine.

**Comment by pjfl** [comment]
And when you try this using a desktop browser set to a narrow width what happens?

**Comment by JB62** [comment]
Oddly, you get a scrollbar for the inner grey section, which scrolls a more smoothly than on a phone, but is still jerky. If you go even smaller, you get two scrollbars - one on the page, one on the grey area.

**Comment by JB62** [comment]
If you get the timing of resizing the browser wider right, you can get  scollbar on just the browser, with the calendar in the middle truncated at the grey square boundary

![trnc](https://cloud.githubusercontent.com/assets/16360425/21962449/6ff07610-db1e-11e6-9baf-abd4f943aaf4.png)

**Comment by JB62** [comment]
Perhaps set a minimum width for the grey area that agrees with the min width of the calendar, forcing the whole page to scroll

**Comment by pjfl** [comment]
No the content is too wide for the screen

**Comment by JB62** [comment]
Exactly, so scroll the screen if necessary rather than trying to scroll the content of an element
