### ISSUE TITLE
Add vehicle used to call log delivery stage

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#152]
Should indicate which vehicle was used for each stage of a delivery. This would ideally be a field pre populated with the service vehicle allocated to the rider/driver but must be editable in the event that they actually use another (their own car for example)

**Comment by JB62** [comment]
It seems the field is there in the schema for "leg" - just needs the dialog populated

**Comment by JB62** [comment]
Might make it a bit more tricky, but ideally the field would allow selection from the list of service vehicles, private vehicles owned by the rider or free-text (in case they use a vehicle that isn't registered in the system), defaulting to the service vehicle they've been assigned .

**Comment by pjfl** [comment]
Still need to default it to the one assigned to the slot that the delivery request date relates to. Also need
to allow the controller to enter some random number plate

**Comment by JB62** [comment]
Awesome. I was just thinking I might take a look later to see if I could work something out.

-----Original Message-----

**Comment by pjfl** [comment]
You can create an adhoc vehicle registration from the delivery stage screen and then select it. Just the default to go
