### ISSUE TITLE
Call report needs to report everything

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#153]
The CSV report for calls needs to list everything about each call - controller, caller, details of every stage the lot..

**Comment by JB62** [comment]
This might be better as a new report -  "Call History" or something

**Comment by pjfl** [comment]
There's a one to many relation between journey and leg. How do you propose I flatten that for a csv?

**Comment by JB62** [comment]
I was thinking each row would be a journey, with columns for the journey details as defined by the schema, then columns for the "leg" data repeated as necessary to accommodate the greatest number of legs in any journey in the result set. This obviously means that no two exports would necessarily have the same number of columns, but I don't think that's necessarily an issue.

Alternatively, and possibly preferably, we could assume two legs for each journey; if there are more than that, write the first and last to the column data, with a text version of the remainder appended to any text in the notes field.
 
Fields:
created, controller, requested, customer, pickup, drop off, priority, original priority, delivered, notes, leg1_operator, leg1_called, leg1_vehicle, leg1_beginning, leg1_ending, leg1_collection_eta, leg1_collected, leg1_delivered, leg1_on_station, leg2_operator, leg2_called, leg2_vehicle, leg2_beginning, leg2_ending, leg2_collection_eta, leg2_collected, leg2_delivered, leg2_on_station, notes
