### ISSUE TITLE
Delivery Report details not quite right

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#156]
The report should show operator names, not short codes - the short code will mean nothing to whoever looks at the csv - we need names.

Any intermediate stages are not shown in the "notes" field. If there are 4 stages, the columns for 1 and 4 are populated, but we need to note the details of the others, I previously suggested by appending plain text to the notes column, but if it's easier just have each leg in it's own set of columns just like the first/last at the moment. That would presumably mean either variable length rows (not great) or padding blank columns (probably not especially great either) to match the longest, although on balance, perhaps the latter is preferable.

I quite like "stage" rather than "leg" as you've used in the code too.

**Comment by JB62** [comment]
Need to add details of what is being delivered too.  This can be a single column - " 1x blood 2x eyes 1x sample "

**Comment by JB62** [comment]
See pull request #157

**Comment by pjfl** [comment]
Fixed in 35f18de
