### ISSUE TITLE
Can't delete a user

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#162]
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::mysql::st execute failed: Cannot delete or update a parent row: a foreign key constraint fails (`schedule`.`event`, CONSTRAINT `event_fk_owner_id` FOREIGN KEY (`owner_id`) REFERENCES `person` (`id`)) [for Statement "DELETE FROM `person` WHERE ( `id` = ? )" with ParamValues: 0='14'] at /notitia/local/lib/App/Notitia/Model/Person.pm line 460

**Comment by pjfl** [comment]
Your point being?
