### ISSUE TITLE
post-install can't create the notitia user

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#164]
$ bin/notitia-cli post-install
Cli: Started by notitia Version 0.12.32 Pid 6145
Schema: Started by notitia Version 0.12.32 Pid 6146
Schema: Database name                  (q to quit) [schedule]: [schedule]
Schema: Driver type                            (q to quit) []: mysql
Schema: Host name                     (q to quit) [localhost]: [localhost]
Schema: Port number                            (q to quit) []: 3306
Schema: User name                              (q to quit) []: notitia
Schema: User password                          (q to quit) []: ********
Schema: Finished in 19 seconds
Schema: Started by notitia Version 0.12.32 Pid 6147

Schema: Need the database administrators id and password to perform a drop
Schema: database operation

Schema: Database administrator id          (q to quit) [root]: admin
Schema: Database administrator password        (q to quit) []: ****************
Schema: Really drop the database                 (y/n, q) [n]: y
Schema: Droping database schedule
Schema: Finished in 14 seconds
Schema: Started by notitia Version 0.12.32 Pid 6154

Schema: Need the database administrators id and password to perform a create
Schema: database operation

Schema: Database administrator id          (q to quit) [root]: admin
Schema: Database administrator password        (q to quit) []: ****************
Schema: Creating mysql database schedule
Schema: ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'if not exists 'notitia'@'localhost' identified by '********'' at line 1 rv 1
Schema: Terminated code 1
Cli: Unknown error rv 1
Cli: Terminated code 1

**Comment by JB62** [comment]
If it helps... 

Server version: 10.0.29-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04

**Comment by pjfl** [comment]
Bollocks my bad solution comming up

**Comment by pjfl** [comment]
Is fixed on Github will release Class::Usul first day of next month. Will leave ticket open till then

**Comment by pjfl** [comment]
Fixed in Class::Usul v0.81.1
