### ISSUE TITLE
Mobile CSS widths

### ISSUE THREAD

**Issue by pjfl** [pjfl/p5-app-notitia#166]
Make the background boxes go full width on mobile
![screenshot_20170430-143342](https://cloud.githubusercontent.com/assets/789224/25564779/66e6ae0e-2db2-11e7-99fc-f2fcbf0f8f4e.png)

**Comment by pjfl** [comment]
This behaviour was altered by #171 and is now not reproducible either by making a regular web browser window smaller or in testing on an Ubuntu phone browser

**Comment by JB62** [comment]
Still happens on a  phone
