### ISSUE TITLE
Move the email template list

### ISSUE THREAD

**Issue by pjfl** [pjfl/p5-app-notitia#168]
Email templates should have a list view in the management section

**Comment by pjfl** [comment]
Which turns out to be a pain in the arse. They are under the posts directory because they have to be "in sight" of the markdown editor, this currently looks at the docs and posts trees. Move the email templates out of the posts tree and we need another class with a new base path and then apply the editor role to that

**Comment by JB62** [comment]
Possibly not the editor role but something else

**Comment by pjfl** [comment]
Different kind of role ::Editor.pm

**Comment by JB62** [comment]
Quite like to bump this up the priority list.  :)
