### ISSUE TITLE
Documentation menu navigation

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#17]
Create a partial tree view with CWD

**Comment by JB62** [comment]
I have a fix for this

**Comment by pjfl** [comment]
This isn't exactly what we discussed but...

It makes the top level of the documentation menu an accordion widget
Clicking on a top level folder expands that folder whilst collapsing all
it's siblings.  Second and third level folders are flattened as before
but they are now visually distinct from the top level ones

If you don't like it let me know, I'll leave this issue open for now

**Comment by JB62** [comment]
No, it's horrible and doesn't actually work if I create a folder in a folder - seems to get itself in a right state and docs disappear.

**Comment by pjfl** [comment]
Could you run notitia-schema backup-data and send me the backup file from var/backups
that way I can restore it and see what your seeing

**Comment by JB62** [comment]
Had to zip it - github doesn't like tgz files.  It seems the doc that went awol is now back but in the wron place an no amount of clicking on Dir1 or Dir2 makes the slightest difference to what's displayed. I can at least view all the docs though.


[Notitia-20160406-222435.tgz.zip](https://github.com/pjfl/p5-app-notitia/files/207449/Notitia-20160406-222435.tgz.zip)

**Comment by pjfl** [comment]
Works just fine. Looks a lot better if you put realistic data in their as well. But I'll pull it anyway

**Comment by JB62** [comment]
Started as...
Dir1
Test C
Test D

Clicked Dir1 and got
Dir1
Dir2
Test B
Test A
Test C
Test D 

Click Dir2 and nothing changes
Click Dir1 and it shuffles about and stops in exactly the same position

At one point Test A vanished

**Comment by pjfl** [comment]
Yes that's about right apart from test A disappearing. As I said the top level folders were an
accordion so were clickable. Clicking them expands that folder collapsing the sibling folders.
Subsequent folders were flattened and were not clickable since they are always shown
expanded

**Comment by JB62** [comment]
I think the biggest problem is that it looks like docs at the same level as a directory are underneath the last directory.  Pehaps if directories were listed last

**Comment by JB62** [comment]
...or if the contents of a directory were indented a bit to make it obvious they are in that directory

**Comment by JB62** [comment]
Leave it as-is; #34 is more important

**Comment by pjfl** [comment]
We now have a plan for this. I'm going to add a slide out menu using css and js
