### ISSUE TITLE
Left Margin 

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#171]
Can we change the style sheet a little so that the "grid" always goes close to the left of the screen?   Adding "margin:10px" to the two places where "max-width:978px" seems to achieve what I'm after....

![screen shot 2017-05-01 at 14 55 37](https://cloud.githubusercontent.com/assets/16360425/25581263/c52616e0-2e7e-11e7-95ed-a22be01783cd.png)

rather than

![screen shot 2017-05-01 at 14 56 05](https://cloud.githubusercontent.com/assets/16360425/25581243/a0b10950-2e7e-11e7-837a-529ab61fb325.png)

**Comment by pjfl** [comment]
Make it look fucking stupid but whatever

**Comment by JB62** [comment]
I don't think it does. I think it's​ looks wrong to waste so much space  on the left. If it is to be centered, the left four-fifths should all expand to make it all fill the width. But whatever.
