### ISSUE TITLE
bin/notitia-schema create-schema fails

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#173]
Installing from scratch, creating the schema fails, throwing an exception before asking for the database credentials. It seems that the app-notitia.json file is being generated with just an sms_password field (no idea where it got that from) and the schema module tries to extract  database dsn info from it, fails, and goes bang.

**Comment by JB62** [comment]
$ bin/notitia-schema create-schema
<snip>
Schema: Need the database administrators id and password
Schema: Path '/notitia/local/var/etc/app-notitia.json' database 'schedule' no credentials
<snip>

$ cat /notitia/local/var/etc/app-notitia.json
{
"sms_password" : "{Twofish2}U2FsdGVkX1/RjVkBFkTyauIzXoJEFrsN+PDUF934u7iwBeWRRFayLw6XUeUZCntWDxMjcTBADc0Nm4d9EA8fP90eEPwletd/uXjFRj6XZKYd6R2fBvvB4rK3weG/eyknMJJT/XDHMlWwub5ZqFZTRGoI9pK5PbxURhmqMEmZq6YyFFi69eIuXMQMdRxURyqt9BnGnBSyx7jYbz82NjmSzQ=="
}

**Comment by pjfl** [comment]
Try following the installation instructions

**Comment by JB62** [comment]
I did. To the letter.

**Comment by pjfl** [comment]
Where does it say notitia-schema create-schema?

**Comment by JB62** [comment]
I was looking why post-install failed with that error. post install runs the schema stuff

**Comment by JB62** [comment]
Just did it for the third time from scratch....

notitia@notitia:~/local$ bin/notitia-cli post-install
Cli: Started by notitia Version 0.12.51 Pid 28728
Cli: Env var PERL5LIB is /notitia/local/lib:/notitia/local/lib/perl5
Cli: Is this correct                             (y/n, q) [n]: y
Cli: Env var PERL_LOCAL_LIB_ROOT is /notitia/local
Cli: Is this correct                             (y/n, q) [n]: y

Cli: The organisation prefix is a two or three character string used by the
Cli: shortcode generator. If should reflect the name of the group operating the
Cli: application

Cli: Enter the organisation prefix             (q to quit) []: obn
Schema: Started by notitia Version 0.12.51 Pid 28730

Schema: Schema creation requires a database, id and password. For Postgres
Schema: the driver is Pg and the port 5432. For MySQL the driver is mysql and
Schema: the port 3306

Schema: Create database schema                   (y/n, q) [n]: y

Schema: Need the database administrators id and password

Schema: Path '/notitia/local/var/etc/app-notitia.json' database 'schedule' no credentials
Schema: Terminated code 1
Cli: Unknown error rv 1
Cli: Terminated code 1

**Comment by pjfl** [comment]
Fixed in v0.12.52
