### ISSUE TITLE
Can't use a remote database

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#174]
When the install creates the schema in mysql, it creates the notitia user in the database with permissions to connect only from the database host rather than the application host.

mysql> select user,host from mysql.user;
+-----------+----------------------------------------------------+
| user      | host                                               |
+-----------+----------------------------------------------------+
| root      | %                                                  |
| mysql.sys | localhost                                          |
| rdsadmin  | localhost                                          |
| notitia   | testmysql.bsyen1tqoeya.eu-west-2.rds.amazonaws.com |
+-----------+----------------------------------------------------+
4 rows in set (0.00 sec)

...should be 
| notitia   | % |

**Comment by pjfl** [comment]
No

**Comment by JB62** [comment]
No what?

**Comment by pjfl** [comment]
No the installer doesn't do that. It assumes you will have everything locally

**Comment by JB62** [comment]
So why does it ask for a hostname?

**Comment by pjfl** [comment]
Because there a field after the @ sign that needs a value

**Comment by JB62** [comment]
If you're going to say it only works locally, you can assume 'localhost' and not ask. This does of course mean the database needs to be on the same machine as the web server, which is just terrible. The bit after the @ should be '%' when creating the user so that user can log in from anywhere.

**Comment by pjfl** [comment]
Upgrade Class::Usul from blead and you can test it

**Comment by JB62** [comment]
Yup. That works.
