### ISSUE TITLE
Dynamic login redirect

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#179]
To display "notices" to people when they log in, it would be convenient to make the login_redirect config dynamic in the sense that, if a specific document exists (docs/notice for instance), then login_redirect points to that, and if it doesn't or is tagged with no role that makes it visible, login_redirect points to the normal place ( month/month_rota )

**Comment by pjfl** [comment]
Something between if already does that and your question died of vague

**Comment by JB62** [comment]
I see you have written some words down, but I have no idea what you've said.
