### ISSUE TITLE
Better contrast in text/vehicle colour

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#185]
Where there is text on a vehicle-colour background, need to make the text colour contrast so it's always legible. This seems to work pretty well...

use Graphics::ColorNames;
sub text_colour {
   my $background = shift;
   my $po = new Graphics::ColorNames( qw( X ) );
   my ($r, $g, $b) = $po->rgb($background);
   my $yiq = (($r*299)+($g*587)+($b*114))/1000;
   return ($yiq >= 128) ? 'black' : 'white';
}

**Comment by JB62** [comment]
Pull request #186

**Comment by pjfl** [comment]
Will merge it after you've fixed the indirect object syntax

**Comment by JB62** [comment]
Not sure I can face fighting git again.


-----Original Message-----
