### ISSUE TITLE
Search or filter option for people menu

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#188]
When there is a large number of people over many pages, it's a pain to page through looking for a specific person or people. A filter option, allowing restriction by  certain fields or perhaps any field in the person table.  

name and badge_id (allowing no id in the filter) for sure, and if possible, postcode, join date, resigned date, email .  Suggest a simple "wildcard" ( * and ? rather than %  _ )  filter string-match. 

Though it would be nice, no desperate need for any complicated AND/OR logic - just a single field selector and what to match against would suffice I think.

**Comment by pjfl** [comment]
We have something similar for log files
