### ISSUE TITLE
Additional service vehicle fields

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#194]
Extra fields for service vehicles to be able to record:

Vehicle Make and Model (distinct fields rather than stuffing it into Notes)

Last Fuel Fill: date
First Operational: date

Next Service due: date
Next Service Miles: number
Current Mileage: number
 [ Calculate miles remaining ]

Tax due: date
MOT due: date
Insurance due: date

Front Tyre Changed: mileage
Front Tyre Expected Life: mileage
[ Calculate Front Tyre remaining: mileage ] 

Rear Tyre Changed: mileage
Rear Tyre Expected Life: mileage
[ Calculate Rear Tyre remaining: mileage ]

**Comment by pjfl** [comment]
Fixed in v0.15.5
