### ISSUE TITLE
Display distortion in Internet Explorer

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#202]
Date picker chopped off in it's prime...

![image](https://cloud.githubusercontent.com/assets/16360425/26753579/1a07cb4e-4861-11e7-877f-89296d617858.png)

**Comment by JB62** [comment]
This seems to be related to the line-height: 28px value in the .rota-date-field style. Removing this makes IE behave properly and does not appear to have any adverse effects on Chrome or FF

**Comment by pjfl** [comment]
Should be fixed in v0.13.26. Please retest

**Comment by JB62** [comment]
line-height property still seems to be there - v 0.13.27

**Comment by lazarus1906** [comment]
Thats not what I asked

**Comment by JB62** [comment]
I upgraded to bleed, tried again, and there is no change. what did you ask?
