### ISSUE TITLE
Slightly confusing key on month view

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#206]
Key at bottom says "C - Claimed no vehicle" which is fine, but there is also a C meaning Controller slot claimed. This has confused some people.

![screen shot 2017-06-03 at 19 25 45](https://cloud.githubusercontent.com/assets/16360425/26756070/94cf4f10-4892-11e7-9a4d-e7a6a1c34478.png)

**Comment by pjfl** [comment]
So explain it to them in the documentation

**Comment by JB62** [comment]
I think it would be better if the text in the key said C -CLAIMED  R - CLAIMED AND VEHICLE REQUESTED, that is, just remove the "NO VEHICLE" text.

**Comment by pjfl** [comment]
msgid "month_rota_table_caption"
msgstr "C -CLAIMED R - CLAIMED AND VEHICLE REQUESTED"

**Comment by JB62** [comment]
Seems a bit daft fixing something by overriding the text rather than making the original text more accurate.

-----Original Message-----
