### ISSUE TITLE
Spreadsheet view - second attempt

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#209]
Spreadsheet / table view should be able to display 7 days across without scrolling in non-mobile view. If necessary, reduce font size and/or column width as the window shrinks but limit to retain legibility or have the whole page scroll rather than a window within the page.

Events should be on a single row per event,limited to 4 rows/events and display the event name rather than the event owner.  Multiple vehicle allocations in one event should be in a scrollable "window" in the row for that event. Clicking the event name should bring up the standard edit-event dialog

There should be a row for the controllers. Clicking a controller name/Vacant entry should bring up a slot claim/relinquish dialog as appropriate

Weekday daytime slots should be unavailable and un-editable unless those dates appear in an "exceptions" table.

Clicking a duty name/Vacant should bring up a slot claim/edit/relinquish dialog as appropriate

If the user has rota manager or fleet manager role,  the vehicle list dropdown to allocate the vehicles should not include vehicles already allocated to another event or duty at that time. If the user does not have either of those roles, the vehicle columns should be un-editable text.

Allocating a vehicle or claiming/editing a duty slot should not result in a complete redraw of the whole page, but just those fields that have changed.

Mock-up attached (ignore the fact that every slot is Monday etc)

![ss](https://cloud.githubusercontent.com/assets/16360425/26760921/085ea4ec-491c-11e7-853c-53f104a143d7.png)

**Comment by pjfl** [comment]
Lets start with "the vehicle list dropdown to allocate the vehicles should not include vehicles already allocated to another event or duty at that time" and "Allocating a vehicle or claiming/editing a duty slot should not result in a complete redraw of the whole page, but just those fields that have changed"

But surely if you've allocated a vehicle the list of available vehicles has changed for all other fields

**Comment by JB62** [comment]
For slots at the same time as the one you're trying to allocate, yes. If you've got vehicles a b and c, and three events, two in the morning one in the  afternoon. When you go to allocate one morning event, the drop down shows a b and c and you choose b. When you allocate the other morning event it would show only a and c, with b missing.  The afternoon event would again show a b and c.



-----Original Message-----

**Comment by pjfl** [comment]
Have you forgotten about the mileage? Assign one vehicle and the mileage needs recalculating, all the select fields need redisplaying. What you end up with is some JS that displays an egg-timer whilst the same async calls for the tables are fired again, when the same response as before comes back it swaps out one frame for another whilst try to avoid some screen flicker. This is just so that Guy doesn't have to see a full screen refresh

**Comment by JB62** [comment]
Well actually he didn't ask for no screen refresh, I did - it's bugged me from the start. It's just really clunky and quite frustrating.

The mileage only needs to be displayed when the drop down is open, so perhaps a local calculation could be done at the time. Or perhaps if the drop downs were links to bring up a window a bit like the claim slot, the selection and mileages could be calculated and displayed outside of the main view.




-----Original Message-----

**Comment by pjfl** [comment]
And then when you post the dialog back you get a full screen refresh. And at that point you get an updated snapshot of the state at that point in time. This will include any new slot claims and vehicle allocations, there is more than just one Guy using this application

When you change the state of the application by assigning a vehicle you cannot determine what the new state is without reselecting it, the state, (or at least a time period delimited chunk like we have here) from the database. Next we need to figure out how much of that display has changed, we have no code for that and no framework support. Switching frames using JS is not so hard, but again we ain't doin it anywhere else in the application

**Comment by pjfl** [comment]
So the page refresh requires some new JS hackery added to mooclasses.js and is one issue, if you really want it open another issue.

Moving on. "the vehicle list dropdown to allocate the vehicles should not include vehicles already allocated to another event or duty at that time"

About the fastest way we have at this time of working that out is to wrap assigning the vehicle in a try catch block and working our way through the fleet each time. I think that that would be cost prohibitive in database terms especially if you see anyone other than Guy looking at this page

**Comment by pjfl** [comment]
And then "Weekday daytime slots should be unavailable and un-editable unless those dates appear in an "exceptions" table." which will require a maintenance screen etc, more work for me. Sure you wouldn't like to use the UKHolidays plugin for that instead?

**Comment by JB62** [comment]
Could this not be calculated and removed from the select locally as the popup is opened?

-----Original Message-----

**Comment by pjfl** [comment]
"There should be a row for the controllers", so you won't be wanting four controllers then?

**Comment by JB62** [comment]
Fine. I imagined just manually importing some data directly into the db every year or two, but if there's an easier way, go for it.

-----Original Message-----

**Comment by JB62** [comment]
One row, listing the controllers next to each other was what I had in mind, but if you can hide/show them one row per controller is okay - it just seemed a bit of a waste of relestate.


-----Original Message-----

**Comment by pjfl** [comment]
Implemented in v0.13.26

**Comment by JB62** [comment]
So have distances disappeared now - can't see them in the dropdowns any longer?

**Comment by lazarus1906** [comment]
Yes

**Comment by JB62** [comment]
That's sad.

**Comment by JB62** [comment]
This view is only available to rota_manager - it needs to have the same visibility as the other rota pages, except that only rot_manager can allocate vehicles etc; joe user can claim slots etc.

**Comment by pjfl** [comment]
That change has been made, against my advice. You shouldn't expect me to commit any more time to this project so I'll ask you to stop opening tickets here, you can configure your own fork to have an issues list, I've already pointed the links in the footer to that

**Comment by JB62** [comment]
Something pissed you off?
