### ISSUE TITLE
Spreadsheet view caches previous screen

### ISSUE THREAD

**Issue by pjfl** [pjfl/p5-app-notitia#210]
When I update a vehicle allocation on the spreadsheet view the allocation is made but the screen requires a reload before it will display the allocation

**Comment by pjfl** [comment]
Which is not present in uat so this is a regression introduced by the ETag headers

**Comment by pjfl** [comment]
Turns out I've not published this bug yet :smile:

**Comment by JB62** [comment]
Oh good. Not least as I have no clue what you're on about. :)

-----Original Message-----
