### ISSUE TITLE
Batch vehicle allocation

### ISSUE THREAD

**Issue by lazarus1906** [pjfl/p5-app-notitia#213]
On the vehicle allocation screen, add a button that begins batch assignment mode. Vehicle allocations update the screen as normal but sets a bool attribute on the slot object that marks the vehicle allocation as imaginary. Since  vehicle allocations are taking place service vehicle availability and handover distances will be recalculated as required. Vehicle allocation emails will not be sent. Multiple assignments can then take place, slot claimed / yield states will update each time an imaginary allocation is made. Once allocations have been made, the commit button will cause the imaginary flag to be removed. When the imaginary flag is removed, the vehicle allocations become real and the emails are sent.

Imaginary vehicle allocations will not be visible to anyone but the rota manager

**Comment by pjfl** [comment]
Implemented in v0.15.16
