### ISSUE TITLE
The "types" view edit

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#24]
Each "type" shows an edit button next to it, but when I click this all I can do is view its name - I can't edit it

**Comment by pjfl** [comment]
But you can delete it

**Comment by JB62** [comment]
Then the button should be "delete" then? It gets you all exited but then... nothing.   ;)

**Comment by pjfl** [comment]
Will change the link to say Delete also

**Comment by JB62** [comment]
Or just "View" on the button?

**Comment by pjfl** [comment]
I might as well make it like the other edit screens with a delete and update button. Then you
could change the type name if you created one with a typo and wanted to fix it rather than
deleting and recreating

**Comment by JB62** [comment]
Winner

**Comment by pjfl** [comment]
On second thoughts it has to be a delete button

**Comment by JB62** [comment]
Just leave as-is and mark "won't fix"
