### ISSUE TITLE
Slot criteria are wrong

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#25]
The driver slot needs category_b and advanced and c_advanced, the rider slots need category_a and m_advanced. At the moment it seems everyone needs a car licence and that's it.

**Comment by JB62** [comment]
[patch.txt](https://github.com/pjfl/p5-app-notitia/files/201272/patch.txt)

**Comment by pjfl** [comment]
Will apply the patch with modifications

**Comment by JB62** [comment]
How about a new DB table slot_criteria ( slot_type,  certification_id )  then the slot_certs can be acquired from there rather than Config.pm.  Would need a new page to edit though.

**Comment by pjfl** [comment]
Just how often are you planning on changing the claim slot criteria? I was thinking that it
would be changing with changes in legislation that filter down after some time to a new
certification type being created and then adding it to the entry in the config file. Then
restart the application. That last step is a thing that you can point to and say no, not having
that, so...

A new persistent object SlotCriteria with attributes role_type_id and certification_type_id it is then

**Comment by JB62** [comment]
Okay. Don't worry about it then

**Comment by pjfl** [comment]
No, no I was serious it's either another object or I add a config file editor and a restart application
button. I prefer to add the object

**Comment by JB62** [comment]
Fine. Object.

**Comment by pjfl** [comment]
Requires another schema update, so you'll need to run deploy-and-populate
