### ISSUE TITLE
Inconsistent host name in urls

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#26]
If I navigate through the system to view all users via the url "http://52.18.55.240/notitia/people", the link from the "roles" and "edit" buttons go to "http://notitia/notitia/role/obnbag" and "http://notitia/notitia/person/obnbag" rather than "http://52.18.55.240/notitia/role/obnbag" and "http://52.18.55.240/notitia/person/obnbag"

**Comment by pjfl** [comment]
I can see that happening on your installation. It does not happen anywhere else, my dev copy or
my vps. That's old code that's been working for some time. Have you edited anything on that copy?
Anything at all?

**Comment by JB62** [comment]
I've edited the .po, added some docs and images.

**Comment by pjfl** [comment]
And by v0.3.36 things are magically working again!
