### ISSUE TITLE
Vehicle assignments

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#30]
Need either a new page that shows all the (non private) vehicles and to whom they are currently assigned, or possibly better, have a section at the bottom of the month view that shows vehicle, current keeper and possibly first part of the postcode?

**Comment by JB62** [comment]
In the "Service Vehicles" page, as well as listing name/reg it should show the current/last assignee

**Comment by JB62** [comment]
How do have a "global" view of all the current vehicle locations?   Need to have an "at-a-glance" view of what is where

**Comment by pjfl** [comment]
The global view of current vehicle keepers is shown on the service vehicle list which provides the
at a glance view of who has what, we don't know where a vehicle is just who should be in
possession of it

Adding individual colours for each vehicle is going to limit the number of service vehicles to the
number of distinct colours on the palette and the month rota view does not show vehicles
assigned to events or vehicle events

**Comment by JB62** [comment]
I don't think individual colours is a problem. There are at least 16 that are readily distinguishable and there should be no restriction on vehicles having duplicate colours - that's up to whoever picks the colours when they create/update the vehicle.

I know the month view doesn't show vehicles currently, but does that mean it can't?

**Comment by pjfl** [comment]
Separate colours for each vehicle is doable, showing that colour on the month rota for slots is easy,
showing that colour for vehicles assigned to an event is possible (but it would have to be a narrow
bar of colour only a few pixels wide). Showing vehicle events, we could add another row to each
day showing the vehicle events. That's a lot of extra work

**Comment by JB62** [comment]
The colours on the main duty slots is the most important bit. A narrow bar of a few pixels on the events is fine. Not sure what you mean by "Showing vehicle events" but it doesn't sound so vital.

**Comment by pjfl** [comment]
Vehicle events are like "Repairs - New clutch"

**Comment by JB62** [comment]
Ah, okay. That's fine. Don't worry about those. If it's on the month page it makes it much easy to assign vehicles between shifts to minimise movements, especially if #40 gets implemented too.

**Comment by JB62** [comment]
Where is the "week rota" menu item meant to be? I can't find a way to navigate to it without manually typing it in the URL

**Comment by pjfl** [comment]
On the month rota page bottom of the right hand navigation list

**Comment by JB62** [comment]
The "select week" menu options don't really work that well; the week
numbers displayed don't change when you select a different month so it's
difficult to navigate to where you want to be.

The prev/next buttons go back and forth by a week at a time, which is
great but not that obvious.  I think the five listed week numbers
displayed should reflect the month in-view, so if you were showing say
May, it would show weeks 19 to 23, if you then clicked June, it would
show 24 to 28 etc. Also, if it was displaying 19-23 and you clicked 19,
perhaps it should change to show 17-21 ?

What do you think?

**Comment by pjfl** [comment]
Yes

**Comment by pjfl** [comment]
Commit 4f352e2 implements this
