### ISSUE TITLE
Need a way to store a vehicles location

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#34]
When a vehicle is in for service, it needs to be "assigned" to a location and unavailable. Similarly, when not assigned for duty, it still needs a location. These locations can be any user, or another free-form identifier (bike shop - could be at any, for instance).

If assigned to a slot, the location is deemed to be that of the rider/driver unless overridden by a specific location. Wondering if we can pretend the location is some kind of mocked-up "event" ?

**Comment by pjfl** [comment]
Implemented in v0.3.75
