### ISSUE TITLE
Exception when logging out

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#35]
Since the change to Model:User::login_action to use 'sched/month_rota'...

Log in as admin
Log out 

I'm sorry Admin, I can't do that
The following exception was thrown

Person 'admin' permission denied
Exception thrown from App-Notitia-Role-PageLoading[71/1]
on 2016-04-10 at 10:59 hours
HTTP status code 403
Have a nice day...

**Comment by pjfl** [comment]
Cannot read private documents when logged
