### ISSUE TITLE
Document permissions

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#49]
Non-public documents and menu items can only be seen by users with "editor" role. Any logged in user should be able to view them, with edit being available to "editor" role

**Comment by pjfl** [comment]
Have you tried setting

   roles: any

in the YAML section of these docuements

**Comment by pjfl** [comment]
Which will be patched to work shortly

**Comment by JB62** [comment]
Weird shit. Added role:any , removed editor role now I can't see any documents at all

**Comment by pjfl** [comment]
It's broke am fixing now

**Comment by pjfl** [comment]
Fixed in v0.3.134. Includes a schema change for TOTP auth
