### ISSUE TITLE
View users permission denied

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#5]
Logged in as a user with "address viewer" role, I can't see anyone's details, even my own.

Go to Admin/All People select "edit" and you're presented with a permission denied exception

**Comment by pjfl** [comment]
Yes address viewer is currently unused, however admin > all people > edit should deny access
to an address viewer. Being an address viewer does allow you to view the contacts list.

Fixing the bug in authorisation to the person summary (month rota > day rota > participents (top
right corner) > View. This was allowing the non existent role 'person_viewer' and should allow
the role 'address_viewer' instead

**Comment by pjfl** [comment]
Patched
