### ISSUE TITLE
SMS/Email message sending

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#50]
It would be very useful to be able to enter a message directly into the send dialog as well as being able to select from a pre-created template. Seems a bit wonky to create the template via the normal docs and save as "draft" to me. Perhaps the send message box could be the editor, allowing you to save the text/md you've entered as a template and/or send as SMS or Email? 

Would be good to be able to click-select the destination too as well as the whole group

**Comment by pjfl** [comment]
Added individual user messages from the contacts list in v0.3.152

**Comment by JB62** [comment]
Nice one dude.

**Comment by pjfl** [comment]
Implemented at v0.3.153

**Comment by JB62** [comment]
"Perhaps the send message box could be the editor, allowing you to save the text/md you've entered as a template and/or send as SMS or Email? "

How do I do that?
