### ISSUE TITLE
Need a vehicle import

### ISSUE THREAD

**Issue by pjfl** [pjfl/p5-app-notitia#51]
We need a vehicle import, to load the service vehicle data. Would someone (JB) produce a suitable
CSV for me to work on?

**Comment by JB62** [comment]
There are only 12 - we can add them by hand can't we?

**Comment by pjfl** [comment]
Getting sick of adding them be hand each time I deploy and populate

**Comment by JB62** [comment]
I don't have them stored anywhere so you can just make it up if you like.
