### ISSUE TITLE
Edit user doesn't return to same page

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#52]
When you have sufficient users to require paging, if you edit a user on, say, page 3, when you close the edit dialog, the paged list returns to the first page not page 3

**Comment by pjfl** [comment]
How do you "close the edit dialog"? I thought that person edit was a page not a dialog. I could try making the page parameter persist across queries in the session, not sure what the side effects might be

**Comment by JB62** [comment]
Okay page. Hit save when you're done and you go back to the star of the list.

**Comment by pjfl** [comment]
Do you mean your clicking 'Update' on the person edit form? It then takes you back to a people list page but will probably forget which page you where on, hence the suggestion to persist the page parameter across requests. Also clicking a right side menu nav link doesn't remember your current page. Problems might arise when your switch between different queries, it would still remember the previous page number

**Comment by JB62** [comment]
Okay. Forget it then.

**Comment by pjfl** [comment]
I agree that it is irritating
