### ISSUE TITLE
No indication of "vehicle required" on month rota for events

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#53]
On the month page, if an event has a vehicle request it ought to be indicated that there is a pending vehicle assignment for one or more events on that day (if there are any). In keeping with the slots, perhaps an orange indicator if there is at least one pending assignment, green if all the requests are satisfied and grey if there are no requests.

**Comment by pjfl** [comment]
I think we've talked about this before. It's definitely missing and implementing it might be easier now I've got more canned queries to work with
