### ISSUE TITLE
Vertical table borders in Explorer

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#55]
Vertical table borders in explorer have disappeared. Missing explorer specific css, c.f. Jekyll

**Comment by pjfl** [comment]
Cannot reproduce

**Comment by JB62** [comment]
I can. When the vertical bars on the laptop suddenly worked.... it was in Google chrome. Still doesn't work in ie

**Comment by JB62** [comment]
It seems to be the table "border-collapse: collapse" attribute that's making the lines disappear. Just deleting that seems to fix it for IE and seems not to have a detrimental effect on chrome

**Comment by pjfl** [comment]
Have removed border-collapse, looks good in all the browsers that I have available including phone and tablet
