### ISSUE TITLE
Assorted navigation improvements

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#56]
"normal" user should not see person list 
Anyone should see the participants for events, but should not be able to view the person summary

**Comment by JB62** [comment]
Rename Admin menu to Management

**Comment by JB62** [comment]
Rename Vehicle Allocation back to Select Week
Add "Vehicle Allocation" menu group containing spreadsheet view for vehicle manager

**Comment by pjfl** [comment]
We should recheck the person summary access. It was already set to person_manger and address_viewer only

**Comment by JB62** [comment]
The problem I think is that "address viewer" can see everything. I think it should just be name, address, postcode, phone numbers and email address
