### ISSUE TITLE
Contact list entries

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#62]
I think the NOK details should not be be in the contact list page. Also, whether or not you can send a message from that list (or anywhere else) should be a distinct role - "message sender" or some such.

**Comment by pjfl** [comment]
If you remove the NOK contact numbers from the contacts list then I don't see the point in the contacts list being there at all

**Comment by JB62** [comment]
So you can send messages and see the contact details of the users

**Comment by JB62** [comment]
Perhaps two permissions roles one, that can see NOK one that can't?

**Comment by JB62** [comment]
The point is that controllers for instance will need access to the phone number of the riders on duty, but probably shouldn't have access to nok info.

**Comment by JB62** [comment]
New thought - the mouseover popup on the "day" rota page for the name that has claimed a slot at the moment just says "Yield this rider slot". Perhaps it could instead give the mobile number for the rider?

**Comment by pjfl** [comment]
Unless that's restricted to controllers only any authenticated user will be able to see the riders phone number

**Comment by JB62** [comment]
Or restricted to those with "view phone number" role?

**Comment by pjfl** [comment]
Adding roles like message_sender and view_phone_number is not the way to go. If, for instance, a controller can send messages and view phone numbers then the permission should be applied to the controller role. If not, when you create a controller, you will have to *remember* to add a list of additional roles, get that wrong (human error) and you have a controller account that won't work properly

**Comment by JB62** [comment]
Not sure i agree, but okay. The finer grained there permissions the better, even if it's more work to set them properly, but okay.
