### ISSUE TITLE
SMS/Email message sending

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#63]
On the message popup, when you select "email", there should be a link to create a new "draft" template rather than having to go back to the docs and create one from there. If we could see these email templates separately and be able to edit/delete them outside of the normal "posts", that would be good. 

What does the "draft" mode mean anyway - the name implies it can be "promoted" to a normal doc at some point, but I can't see how to do that. Can we just have "email template" documents, which are only visible/editable to "message senders" ? Perhaps a new section in the right-hand menu in the "admin" pages?

**Comment by pjfl** [comment]
You promote a draft to a visible document by renaming it and removing drafts from the pathname. There is no need to do this for email drafts

**Comment by JB62** [comment]
I just don't see the point.

**Comment by JB62** [comment]
Can we just have "email template" docs, "post" docs, and "information" docs ?

**Comment by pjfl** [comment]
Try adding a second edit email dialog
