### ISSUE TITLE
Password reset email not sent

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#7]
I can't seem to log in to a fresh install as admin/12345678

If I try to reset the password with "forgotten password", it shits all over the browser with

4.1.8 : Sender address rejected: Domain not found Trace begun at /home/ubuntu/local/lib/perl5/Email/Sender/Transport/SMTP.pm line 180 Email::Sender::Transport::SMTP::send_email('Email::Sender::Transport::SMTP=HASH(0x6f31948)', 'Email::Abstract=ARRAY(0x6e0cff0)', 'HASH(0x6f64978)') called at /home/ubuntu/local/lib/perl5/Email/Sender/Role/CommonSending.pm line 45 Email::Sender::Role::CommonSending::try {...} at /home/ubuntu/local/lib/perl5/Try/Tiny.pm line 87 eval {..

when trying to send the email because the mail exchanger, quite understandably,  doesn't like the sender email address - "UserRegistration@" - the domain seems to be missing.

**Comment by pjfl** [comment]
You've never been able to login as admin/12345678. After an install you can use that to
change the password via the change password screen.

**Comment by JB62** [comment]
What about the email exception?
