### ISSUE TITLE
Label names in Person dialog

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#73]
...don't respect the values in notitia.po.  I was looking t have "Coordinates" labelled as "Eastings/Northings" since that's what they are...  but the labels seem to be fixed.

**Comment by pjfl** [comment]
Works for me. Are you running the latest version of File::DataClass

**Comment by pjfl** [comment]
Also the string "Coordinates" with that capitalization only appears in the po file, so it has to be coming from there. You should be editing the notitia_local.po file any why otherwise your changes will not survive an upgrade. You do know that you have to restart the app after editing a po file?

**Comment by JB62** [comment]
Can't tell now. I stupidly upgraded the os to xenial, now feck all will run. cpanm throws an unresolved external error in XS somewhere, you gave to start X manually... it's shot.

**Comment by JB62** [comment]
Okay, cleared out "local" and rebuilt it. All is well. Sorry for the false alarm.
