### ISSUE TITLE
User activity

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#74]
Might be nice to have an explicit user "activity" log so we can get an audit trail of who did what when...

2016-07-04 11:11:09 user:18 client:172.16.16.2 action:slotclaim slot:6.0
2016-07-04 11:23:09 user:35 client:12.11.33.22 action:vehicleasignment slot:6.0 vehicle:27

etc...

**Comment by pjfl** [comment]
This only logs the two actions specified above. You need to specify additional actions to log

**Comment by JB62** [comment]
They were just examples. It would be ideal to log everything that changes any data...

Claim a slot, relinquish a slot, assign a vehicle, unassign a vehicle, edit an event, join an event, leave an event, send a message, edit a document, edit a user, edit a certification, assign/remove a role...  edit includes create and delete.

**Comment by pjfl** [comment]
Implemented in v0.3.256. Requires an update to the installed dependencies
