### ISSUE TITLE
Reporting and statistics package

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#76]
Generate reports from the data in the database.  Initial list might be...

for each person
   no rider slots taken in a given period 
   no controller slots taken in a given period 
   no driver slots taken in a given period 
   no events attended in a given period 

For each vehicle
   how many rider allocations
   how many events

For a given period
   how many rider/driver slots fulfilled vs. how many available
   
for each of active-people, riders, drivers, controllers, fundraiser
  How many total "now"
  How many started in a given period 
  How many resigned in a given period

**Comment by pjfl** [comment]
For a given period how many rider/driver slots fulfilled vs. how many available. Define what is meant by how may available. Do you want me to not count the day slots mon-fri?

**Comment by JB62** [comment]
That's right, though quite how you account for bank holidays I'm not sure. Perhaps gloss over those as it's not going to make a massive difference in the grand scheme of things.

**Comment by pjfl** [comment]
Try the reports branch. Pull from github, then git checkout reports, restart your dev server. Remember
to git checkout master before making any changes not associated with the reports branch

**Comment by JB62** [comment]
I seem to need a database schema update - logs are saying "please call upgrade on the database schema" but I'm on 258 and that's the latest sql file I've got

**Comment by pjfl** [comment]
Schema v0.3.258 is the latest and the reports model doesn't introduce any schema changes. Don't know why your getting that error

**Comment by pjfl** [comment]
Try setting DBIC_TRACE=1 and restarting the dev server. You will be able to see the couple of queries the versioned code makes on database connect. It's those queries that are triggering the error

**Comment by pjfl** [comment]
Also according to the source the error message you got contains both the schema version and the database version numbers which would be really useful

**Comment by JB62** [comment]
Looks like i messed up the last upgrade. Basically, it didn't work as i didn't have the old SQL but i didn't notice. I've exported what's there, then imported again and all's well.

Reports look fine, but might be useful if we can "view as text" or something so we can copy and paste into an email.  Or better perhaps, save as csv so can import into excel and create charts.

**Comment by pjfl** [comment]
So a download as csv button it is. I've already added a media query to the css so you can print them out

**Comment by pjfl** [comment]
Added download CSV buttons

**Comment by pjfl** [comment]
So shall I merge this branch into master? No schema changes required

**Comment by JB62** [comment]
Absolutely.
