### ISSUE TITLE
Call logging

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#77]
Facility for a controller to log every call that comes in.  A controller should be able to edit their own reports only within 30 minutes - after that, it becomes read-only.

Must allow controller to enter:
date and time
who placed the call (select from a list with manually-entered value available)
where the consignment is to be collected from (same list as above)
where the consignment is to be delivered to (same list as above)
rendezvous location (if appropriate) 
what the consignment is - checkbox list including "other"
priority - one of routine, urgent, emergency
original priority - same list as priority or blank - filled in if the priority changed during the run
completed - yes or no
rider/driver
time rider called
eta for collection
actual time collected
actual time delivered
actual time rider at base after run
vehicle used - serv bike, private bike, private car
comments

Optional fields
second rrider/driver
time second rider called
actual time second rider collected
actual time  second rider delivered
actual time  second rider rider at base after run
second rider vehicle used - serv bike, private bike, private car

**Comment by pjfl** [comment]
Take a look at this [gist](https://gist.github.com/pjfl/4fa21f83722531abda2edd5c33d321a3). Let me know if you think it will capture the data for what your wanting here

**Comment by pjfl** [comment]
First issue. Can I assume that the rendezvous locations will have a postcode? If I can then we can calculate distance for each leg of a journey. If not then assuming I can have postcodes for pickup and dropoff, we can have distances for the whole journey.

Second issue. The 'who placed the call' attribute (more like 'who requested the journey be made'). Do you want to associate specific default pickup and dropoff locations with this 'who...' of which we speak? I'm thinking the field for this on the form is a select list with an 'Add new' link next to it. The 'Add new' link pops up a modal dialog letting you enter the 'who...' and select a default pickup and dropoff location. When you select that 'who...' we can pre-fill the pickup and dropoff locations for the journey

**Comment by JB62** [comment]
We have 3 "standard" rendezvous - Swindon general hospital, Tesco just off the m6, and Brackley BP garage, though there may be others on an ad hoc basis. No clue what the postcodes are but we can find out for the standard ones, but can't expect the controller find out for as hoc ones.

Default values would be good if they didn't lead to errors. If the user has to fill it in, the chances are they'll put the right value in. If it's got a default, they may easily slip over it and leave the default, but in that instance wrong, value. So no, no defaults i think.

**Comment by JB62** [comment]
Not sure we can the location keyed on postcode - for the "other" location, we might not know the postcode, or a real address for that matter - it's more likely to be "Horton Ward 3" or something. If the address can be free form with NP expected format, that's fine, but really not sure we can rely on a postcode.

**Comment by pjfl** [comment]
When delivery complete allow controller to update on_station for 24hrs then disable updates.
Add role to allow viewing on 24hr old completed deliveries.
A controller should only be able to view/edit their on delivery requests and incidents

**Comment by JB62** [comment]
Just one thing - we can and do carry more than one package at a time. While we can work around it selecting a "main" type and filling out the the notes field with further info, it would be better to be able to explicitly list the packages and types. Often this might be one whole blood, one platelets for example.

**Comment by pjfl** [comment]
More than one package type would mean adding another table
