### ISSUE TITLE
Posts permissions

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#83]
I should not be able to read "posts" when not logged in... but I can.

**Comment by pjfl** [comment]
The posts are advertising a fund raising event they are meant to be on anonymous access. The link in the rss feed takes you to the post, the link in the post takes you to the event participation page via the login page

**Comment by JB62** [comment]
Not sure - perhaps, but "bike in for service" certainly shouldn't be a public event. Probably don't want people signing up for it either.

**Comment by pjfl** [comment]
Vehicle events don't generate posts and you cannot participate in them, they have a separate event type

**Comment by JB62** [comment]
https://notitia.j-bg.co.uk/notitia/posts/index - "Service Edith"

**Comment by pjfl** [comment]
"Service Edith" is a person event. You create a vehicle event via the service vehicles menu option

**Comment by JB62** [comment]
Don't know how that got there then.

**Comment by pjfl** [comment]
I think I can change this to work the way you wanted. I think I can arrange it so that when you click the link in the feed reader it sticks the uri for the post in session wanted, redirects to the login page and then after successful login redirect to the post page

**Comment by pjfl** [comment]
New event posts will be created role: any forcing a login before viewing
