### ISSUE TITLE
Indication on who is logged in

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#86]
Would be good if the UI somehow indicated who was currently logged in - just the name, perhaps at the bottom of the page?

**Comment by pjfl** [comment]
Not sure how too style a list of say fifty names at the bottom of the page. Which page was that? All pages perhaps?

Then there's the concept of "currently logged in". The application isn't keeping a record (other than the log files), you wouldn't expect most users to logout so their is no logout record in the log. Sessions expire when the user next tries to use that (expired) session. So, currently, the application does not support the concept of "currently logged in".

**Comment by JB62** [comment]
I doubt it will be 50 at a time. 5 maybe. How about "did something in the last n minutes". Give a count and the most recent three ...  "aaa, bbb, ccc and 7 others".  ?

**Comment by JB62** [comment]
There's no need to persist any data - just in memory info perhaps on a global object.

**Comment by pjfl** [comment]
We could tail the last five lines of the activity log and process that into a list of names and actions
