### ISSUE TITLE
POSTS menu gets unmanageable when there are a large number of events

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#95]
The menu seems to be ever expanding. If there are 300 events coming up, then the menu continues past the end of the page to the centre of the earth.  Well, not quite, but you get what I mean.

**Comment by JB62** [comment]
I think we either need to limit the number of entries, or group by date somehow.

**Comment by JB62** [comment]
Tempted to think we should revert "POSTS" back to "EVENTS" too. Sorry.

**Comment by pjfl** [comment]
There is a hard coded limit of 100 entries in ::PageLoading::navigation. Will make this the 113th config attribute.

If we rename posts back to events then the draft emails will look out of place

**Comment by pjfl** [comment]
The config option is already in scope under a different key. In the config file

       "components": {
      "Model::Posts": {
         "feed_subtitle": "Recent news and events",
         "feed_title": "Blood Bike Events",
         "max_navigation": 20
      }

Limits the maximum number of post entries to 20 (which is the default)
