### ISSUE TITLE
Footer activity link too free with it's info

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#97]
This new link seems to just give all the actions in the log to all and sundry - this is not good. Just need to show recent login names and count, not the whole log info.

**Comment by pjfl** [comment]
It show the last three activities for the last five users, thats all

**Comment by pjfl** [comment]
Who would you like access restricted to?

**Comment by JB62** [comment]
It shouldn't show activities, literally just the names of those active. That's it, not "fred added a role" etc.

**Comment by JB62** [comment]
...so Just the text "Recently active users: Admin User, Joe Bloggs, Pauline Purple"   or something like that.

**Comment by JB62** [comment]
Sorry, still don't like this. I was hoping for, literally, some text at the bottom of the page - something like "Recently active users: Admin User, Joe Bloggs, Pauline Purple" rather than a link. #86 was meant to describe that, but I don't think I managed to get it across very well.
