### ISSUE TITLE
Means of navigating away from spreadsheet view

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#98]
Since the menu is no longer available in this view, can we have a link somewhere to return to the "month" view rather than having to click "Rota" top menu and navigating through again?

**Comment by JB62** [comment]
Similarly, a link on the "Day" view to return to the month view

**Comment by pjfl** [comment]
The rota link takes you to the month view, so don't understand why you would want another link to it

**Comment by pjfl** [comment]
The day view has right side navigation, there is already a link there to take you to the month view

**Comment by JB62** [comment]
So it's obvious.
